# Generated by Django 3.1.2 on 2020-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_pedido', models.DateField()),
                ('nome_do_cliente', models.CharField(max_length=64, null=True)),
                ('canal_da_venda', models.CharField(max_length=32, null=True)),
                ('modelo', models.CharField(choices=[('Manga-Longa', 'Manga-Longa'), ('Baby-Look', 'Baby-Look'), ('Normal', 'Camiseta Normal'), ('Moletom', 'Moletom'), ('Bag', 'Shoulder-Bag'), ('Pochete', 'Pochete')], max_length=32, null=True)),
                ('estampa', models.CharField(blank=True, max_length=32, null=True)),
                ('tamanho', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'GG'), ('XL', 'Extra-Grande'), ('XXL', 'XXL')], max_length=8, null=True)),
                ('cor_tecido', models.CharField(blank=True, max_length=16, null=True)),
                ('cor_estampa', models.CharField(blank=True, max_length=16, null=True)),
                ('modo_pagamento_padrao', models.CharField(choices=[('bb_laura', 'Banco do Brasil - Laura'), ('nu_pato', 'Nubank - Pato'), ('cx_laura', 'Caixa Federal - Laura'), ('din_pato', 'Dinheiro - Pato'), ('din_laura', 'Dinheiro - Laura'), ('banri_pato', 'Banrisul - Pato'), ('pag_seg', 'Pagseguro - Little Ugly'), ('pic_pay_laura', 'PicPay - Laura'), ('pag_irregular', 'Pagamento Irregular')], max_length=32, null=True)),
                ('modo_pagamento_irregular', models.CharField(blank=True, max_length=32, null=True)),
                ('pagamento_efetuado', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=8, null=True)),
                ('frete', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=8, null=True)),
                ('valor_frete', models.FloatField(blank=True, null=True)),
                ('tipo_frete', models.CharField(blank=True, choices=[('bike_tele', 'Tele de Bike'), ('PAC', 'PAC'), ('Sedex', 'Sedex')], max_length=32, null=True)),
                ('valor_total', models.FloatField(null=True)),
                ('mouse_data_pedido', models.DateField(blank=True, null=True)),
                ('mouse_pronta', models.DateField(blank=True, null=True)),
                ('entregue', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=8, null=True)),
                ('modo_entrega', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
