# Generated by Django 3.1.2 on 2020-11-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='cor_estampa',
            new_name='cor_da_estampa',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='cor_tecido',
            new_name='cor_do_tecido',
        ),
    ]
