# Generated by Django 3.1.2 on 2020-11-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0002_auto_20201124_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='modo_pagamento_padrao',
            new_name='modo_de_pagamento',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='modo_pagamento_irregular',
            new_name='pagamento_irregular',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='tipo_frete',
            new_name='tipo_de_frete',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor_frete',
            new_name='valor_do_frete',
        ),
    ]
