# Generated by Django 3.1.2 on 2020-11-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0003_auto_20201124_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='mouse_data_pedido',
            new_name='data_da_finalizacao_mouse',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='mouse_pronta',
            new_name='data_do_pedido_mouse',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='modo_entrega',
            new_name='modo_de_entrega',
        ),
    ]
