# Generated by Django 3.1.2 on 2020-11-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0004_auto_20201124_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_da_finalizacao_mouse',
            new_name='data_da_finalizacao_na_Mouse',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='data_do_pedido_mouse',
            new_name='data_do_pedido_na_Mouse',
        ),
    ]
