# Generated by Django 3.1.2 on 2020-11-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0005_auto_20201124_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='entregue',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='frete',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(choices=[('Manga-Longa', 'Manga-Longa'), ('Baby-Look', 'Baby-Look'), ('Normal', 'Camiseta Normal'), ('Moletom', 'Moletom'), ('Bag', 'Shoulder-Bag'), ('Pochete', 'Pochete'), ('Touca', 'Touca')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pagamento_efetuado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=8, null=True),
        ),
    ]
