# Generated by Django 3.1.2 on 2020-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0006_auto_20201124_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_do_cliente',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='Um', max_length=8, null=True),
        ),
    ]
