# Generated by Django 3.1.2 on 2020-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0007_auto_20201125_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_do_pedido',
            field=models.DateTimeField(),
        ),
    ]
