# Generated by Django 3.1.2 on 2020-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0008_auto_20201125_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_do_pedido',
            field=models.DateField(),
        ),
    ]
