# Generated by Django 3.1.2 on 2020-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0010_auto_20201125_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='modo_de_pagamento',
            field=models.CharField(blank=True, choices=[('bb_laura', 'Banco do Brasil - Laura'), ('nu_pato', 'Nubank - Pato'), ('cx_laura', 'Caixa Federal - Laura'), ('din_pato', 'Dinheiro - Pato'), ('din_laura', 'Dinheiro - Laura'), ('banri_pato', 'Banrisul - Pato'), ('pag_seg', 'Pagseguro - Little Ugly'), ('pic_pay_laura', 'PicPay - Laura'), ('pag_irregular', 'Pagamento Irregular')], max_length=32, null=True),
        ),
    ]
