# Generated by Django 3.1.2 on 2020-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0012_auto_20201125_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='estampa',
            name='nome_da_estampa',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
