# Generated by Django 3.1.2 on 2020-11-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0013_estampa_nome_da_estampa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(choices=[('Manga-Longa', 'Manga-Longa'), ('Baby-Look', 'Baby-Look'), ('Camiseta Normal', 'Camiseta Normal'), ('Moletom', 'Moletom'), ('Shoulder-Bag', 'Shoulder-Bag'), ('Pochete', 'Pochete'), ('Touca', 'Touca')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modo_de_pagamento',
            field=models.CharField(blank=True, choices=[('Banco do Brasil - Laura', 'Banco do Brasil - Laura'), ('Nubank - Pato', 'Nubank - Pato'), ('Caixa Federal - Laura', 'Caixa Federal - Laura'), ('Dinheiro - Pato', 'Dinheiro - Pato'), ('Dinheiro - Laura', 'Dinheiro - Laura'), ('Banrisul - Pato', 'Banrisul - Pato'), ('Pagseguro - Little Ugly', 'Pagseguro - Little Ugly'), ('PicPay - Laura', 'PicPay - Laura'), ('Pagamento Irregular', 'Pagamento Irregular')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XL', 'XL'), ('XXL', 'XXL'), ('Único', 'Único')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_de_frete',
            field=models.CharField(blank=True, choices=[('Tele de Bike', 'Tele de Bike'), ('PAC', 'PAC'), ('Sedex', 'Sedex')], max_length=32, null=True),
        ),
    ]
