# Generated by Django 3.1.2 on 2020-11-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0014_auto_20201125_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estampa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos_feios.estampa'),
        ),
    ]
