# Generated by Django 3.1.2 on 2020-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0016_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='estampa',
            name='nome_da_estampa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
