# Generated by Django 3.1.2 on 2020-11-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0020_auto_20201125_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='pagamento_irregular',
        ),
    ]
