# Generated by Django 3.1.2 on 2020-11-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0021_remove_produto_pagamento_irregular'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFrete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_frete', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_de_frete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos_feios.tipofrete'),
        ),
    ]
