# Generated by Django 3.1.2 on 2020-11-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0025_auto_20201126_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalvenda',
            name='canal_da_venda',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='canal_da_venda',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos_feios.canalvenda'),
        ),
    ]
