# Generated by Django 3.1.2 on 2020-11-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0026_auto_20201127_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estampa',
            old_name='nome_da_estampa',
            new_name='estampa',
        ),
    ]
