# Generated by Django 3.1.2 on 2020-11-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0027_auto_20201127_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagamento',
            new_name='ModoDePagamento',
        ),
        migrations.RenameField(
            model_name='mododepagamento',
            old_name='pagamento',
            new_name='modo_de_pagamento',
        ),
    ]
