# Generated by Django 3.1.2 on 2020-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_feios', '0029_auto_20201207_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalvenda',
            name='canal_da_venda',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
